[package]
name = "kithara-abr"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Protocol-agnostic adaptive bitrate algorithm for audio streaming"

[dependencies]
tracing = { workspace = true }

[dev-dependencies]
unimock = { workspace = true }
rstest = { workspace = true }

[lints]
workspace = true
