[package]
name = "kithara-hls"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
kithara-assets = { workspace = true }
kithara-net = { workspace = true }
kithara-stream = { workspace = true }
kithara-storage = { workspace = true }
kithara-worker = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
hls_m3u8 = { workspace = true }
hex = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
url = { workspace = true }
async-stream = { workspace = true }
tracing = { workspace = true }
async-trait = { workspace = true }
aes = { workspace = true }
cbc = { workspace = true }
dashmap = { workspace = true }
parking_lot = { workspace = true }
mockall = { workspace = true }

[features]
default = []

[dev-dependencies]
kithara-net = { workspace = true, features = ["test-utils"] }
axum = { workspace = true }
tempfile = { workspace = true }
rodio = { workspace = true }
tracing-subscriber = { workspace = true }
rstest = { workspace = true }
