[package]
name = "kithara-bufpool"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
description = "Generic sharded buffer pool for zero-allocation hot paths"

[dependencies]
kithara-platform = { workspace = true }
derivative = { workspace = true }
hotpath = { workspace = true, optional = true }

[features]
perf = ["dep:hotpath", "hotpath/hotpath"]


[lints]
workspace = true
