[package]
name = "kithara-events"
version = "0.1.0"
edition.workspace = true
authors.workspace = true
license.workspace = true
description = "Unified event bus for kithara audio pipeline"

[lints]
workspace = true

[dependencies]
tokio = { workspace = true }

kithara-abr = { workspace = true, optional = true }
kithara-decode = { workspace = true, optional = true }

[features]
default = ["hls", "audio"]
hls = ["dep:kithara-abr"]
audio = ["dep:kithara-decode"]

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
