[package]
name = "kithara-assets"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
kithara-core = { workspace = true }
kithara-storage = { workspace = true }
thiserror = { workspace = true }
uuid = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
url = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }

[dev-dependencies]
tempfile = { workspace = true }
