[package]
name = "kithara-stream"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Streaming orchestration (source -> bytes stream) with sync Read+Seek"

[lints]
workspace = true

[dependencies]
async-stream = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
kithara-assets = { workspace = true }
kithara-net = { workspace = true }
kithara-storage = { workspace = true }
parking_lot = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
hotpath = { workspace = true, optional = true }

[features]
perf = ["dep:hotpath", "hotpath/hotpath"]

[dev-dependencies]
tokio = { workspace = true }
rstest = { workspace = true }
memory-stats = { workspace = true }
axum = { workspace = true }
mockall = { workspace = true }
tempfile = { workspace = true }
