[package]
name = "kithara-stream"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"
description = "Streaming orchestration (source -> bytes stream) with command/control channel"

[lints]
workspace = true

[dependencies]
async-stream = { workspace = true }
async-trait = { workspace = true }
bytes = { workspace = true }
futures = { workspace = true }
kanal = { workspace = true }
kithara-assets = { workspace = true }
kithara-bufpool = { workspace = true }
kithara-net = { workspace = true }
kithara-storage = { workspace = true }
kithara-worker = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }

[dev-dependencies]
tokio = { workspace = true }
rstest = { workspace = true }
memory-stats = { workspace = true }
axum = { workspace = true }
mockall = { workspace = true }
