[package]
name = "kithara-file"
version = "0.1.0"
edition = "2024"
license = "MIT OR Apache-2.0"

[dependencies]
bytes = { workspace = true }
kithara-assets = { workspace = true }
kithara-net = { workspace = true }
kithara-stream = { workspace = true }
kithara-storage = { workspace = true }
futures = { workspace = true }
thiserror = { workspace = true }
tokio = { workspace = true }
tokio-util = { workspace = true }
tracing = { workspace = true }
url = { workspace = true }
dhat = { workspace = true, optional = true }

[dev-dependencies]
# Keep dev deps workspace-first; add here only after adding to root [workspace.dependencies].
axum = { workspace = true }
rodio = { workspace = true }
rstest = { workspace = true }
tempfile = { workspace = true }
tracing-subscriber = { workspace = true }
memory-stats = { workspace = true }
reqwest = { workspace = true }
mockall = { workspace = true }
dhat = { workspace = true }
